version: '2'

services:
  saga:
    build: sagaExample
    ports:
      - 8001:8001
    volumes:
      - ./sagaExample:/usr/src/app
      - /usr/src/app/node_modules

  thunk:
    build: basicActionsExample
    ports:
      - 8000:8000
    volumes:
      - ./basicActionsExample:/usr/src/app
      - /usr/src/app/node_modules