export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const ON_LEAVE_LOGIN = 'ON_LEAVE_LOGIN';
export const ON_LEAVE_SIGNUP = 'ON_LEAVE_SIGNUP';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGOUT = 'LOGOUT';

export const REQUEST_TERMS_ACCEPTANCE = 'REQUEST_TERMS_ACCEPTANCE';
export const ON_TERMS_ACCEPTED = 'ON_TERMS_ACCEPTED';